name: My first workflow 
on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: Actions/Checkout@main

            - name: welcome message 
              run: echo "My first Github Actions"
            
            - name: List of file
              run: ls 
              
            - name : View the file 
              run : cat README.md